// mobile/app/(tabs)/diet.tsx
import { useState, useEffect, useCallback } from 'react'
import { View, Text, ScrollView, StyleSheet, TouchableOpacity, Image, ActivityIndicator } from 'react-native'
import AsyncStorage from '@react-native-async-storage/async-storage'
import { useFocusEffect } from 'expo-router'
import { getProfile } from '../../lib/supabase'
import { generateMealPlan, MealPlan } from '../../lib/api'
import { calcProfile } from '../../lib/calc'
import { router } from 'expo-router'

const MEAL_COLORS: Record<string, string> = {
  breakfast: '#F59E0B', lunch: '#10B981', dinner: '#7C5CFC', snack: '#3B82F6'
}

export default function DietScreen() {
  const [plan, setPlan]         = useState<MealPlan | null>(null)
  const [loading, setLoading]   = useState(false)
  const [error, setError]       = useState('')
  const [provider, setProvider] = useState('')
  const [targets, setTargets]   = useState({ calories: 0, protein: 0, carbs: 0, fat: 0 })
  const [planUpdated, setPlanUpdated] = useState(false)

  // Load profile targets once
  useEffect(() => {
    getProfile().then(p => {
      if (p) {
        const c = calcProfile(p.gender, p.age, p.height_cm, p.weight_kg, p.activity, p.goal)
        // calcProfile returns { calories, macros: { protein, carbs, fat }, bmr, tdee, bmi }
        setTargets({ calories: c.calories, protein: c.macros.protein, carbs: c.macros.carbs, fat: c.macros.fat })
      }
    })
  }, [])

  // Reload meal plan every time this tab is focused — picks up AI coach updates instantly
  useFocusEffect(
    useCallback(() => {
      AsyncStorage.getItem('meal_plan').then(p => {
        if (p) {
          const parsed = JSON.parse(p)
          setPlan(prev => {
            if (prev && JSON.stringify(prev) !== JSON.stringify(parsed)) {
              setPlanUpdated(true)
              setTimeout(() => setPlanUpdated(false), 4000)
            }
            return parsed
          })
          setProvider(parsed._provider || '')
        }
      })
    }, [])
  )

  const generate = async () => {
    setLoading(true); setError('')
    try {
      const profile = await getProfile()
      if (!profile) { setError('Complete your profile first.'); setLoading(false); return }
      const calc = calcProfile(profile.gender, profile.age, profile.height_cm, profile.weight_kg, profile.activity, profile.goal)
      const res = await generateMealPlan({
        calories: calc.calories,
        protein: calc.protein,
        carbs: calc.carbs,
        fat: calc.fat,
        restrictions: profile.dietary_restrictions || 'none',
        gender: profile.gender || 'male'
      })
      setPlan(res)
      setProvider(res._provider || '')
      setTargets(calc)
      await AsyncStorage.setItem('meal_plan', JSON.stringify(res))
    } catch (e: any) {
      setError(e.message)
    }
    setLoading(false)
  }

  const totals = plan?.daily_totals

  return (
    <ScrollView style={s.scroll} showsVerticalScrollIndicator={false}>
      {/* Hero */}
      <View style={s.hero}>
        <Image source={require('../../assets/hero_nutrition.png')} style={s.heroBg} />
        <View style={s.heroOverlay} />
        <View style={s.heroContent}>
          <Text style={s.heroLabel}>Daily Nutrition</Text>
          <Text style={s.heroTitle}>Your Meal Plan</Text>
          {provider ? <Text style={s.heroSub}>Generated by {provider}</Text> : null}
        </View>
      </View>

      <View style={s.body}>
        {/* Target Summary */}
        {targets.calories > 0 && (
          <View style={s.targetCard}>
            <Text style={s.targetTitle}>Daily Targets</Text>
            <View style={s.targetRow}>
              {[
                { label: 'Calories', value: `${targets.calories}`, unit: 'kcal', color: '#F59E0B' },
                { label: 'Protein', value: `${targets.protein}`, unit: 'g', color: '#7C5CFC' },
                { label: 'Carbs', value: `${targets.carbs}`, unit: 'g', color: '#10B981' },
                { label: 'Fat', value: `${targets.fat}`, unit: 'g', color: '#EF4444' },
              ].map(t => (
                <View key={t.label} style={s.targetItem}>
                  <Text style={[s.targetVal, { color: t.color }]}>{t.value}</Text>
                  <Text style={s.targetUnit}>{t.unit}</Text>
                  <Text style={s.targetLabel}>{t.label}</Text>
                </View>
              ))}
            </View>
          </View>
        )}

        {error ? <Text style={s.error}>{error}</Text> : null}

        {planUpdated && (
          <View style={s.updatedBanner}>
            <Text style={s.updatedText}>✦ Meal plan updated by AI Coach</Text>
          </View>
        )}

        <TouchableOpacity style={s.genBtn} onPress={generate} disabled={loading}>
          {loading
            ? <><ActivityIndicator color="#fff" size="small" /><Text style={s.genBtnText}>  Generating...</Text></>
            : <Text style={s.genBtnText}>{plan ? 'Regenerate Meal Plan' : 'Generate My Meal Plan'}</Text>
          }
        </TouchableOpacity>

        <TouchableOpacity style={s.coachBtn} onPress={() => router.push('/(tabs)/chat')}>
          <Text style={s.coachBtnText}>Customize with AI Coach</Text>
        </TouchableOpacity>

        {/* Meals */}
        {plan?.meals?.map((meal, i) => {
          const color = MEAL_COLORS[meal.type] || '#7C5CFC'
          return (
            <View key={i} style={s.mealCard}>
              <View style={s.mealHeader}>
                <View style={[s.mealTag, { backgroundColor: color + '22', borderColor: color + '55' }]}>
                  <Text style={[s.mealTagText, { color }]}>{meal.type?.toUpperCase()}</Text>
                </View>
                <Text style={s.mealCal}>{meal.calories} kcal</Text>
              </View>
              <Text style={s.mealName}>{meal.name}</Text>
              <View style={s.macroChips}>
                <Text style={s.macroChip}>P {Math.round(meal.protein)}g</Text>
                <Text style={s.macroChip}>C {Math.round(meal.carbs)}g</Text>
                <Text style={s.macroChip}>F {Math.round(meal.fat)}g</Text>
                {meal.prep_time_min && <Text style={s.macroChip}>{meal.prep_time_min} min</Text>}
              </View>
              {meal.ingredients?.length > 0 && (
                <View style={s.ingredients}>
                  {meal.ingredients.map((ing, j) => (
                    <Text key={j} style={s.ingredient}>· {ing}</Text>
                  ))}
                </View>
              )}
            </View>
          )
        })}

        {/* Daily Totals */}
        {totals && (
          <View style={s.totalsCard}>
            <Text style={s.totalsTitle}>Daily Totals</Text>
            <View style={s.totalsRow}>
              {[
                { label: 'Calories', value: totals.calories, unit: 'kcal' },
                { label: 'Protein', value: Math.round(totals.protein), unit: 'g' },
                { label: 'Carbs', value: Math.round(totals.carbs), unit: 'g' },
                { label: 'Fat', value: Math.round(totals.fat), unit: 'g' },
              ].map(t => (
                <View key={t.label} style={s.totalItem}>
                  <Text style={s.totalVal}>{t.value}{t.unit}</Text>
                  <Text style={s.totalLabel}>{t.label}</Text>
                </View>
              ))}
            </View>
          </View>
        )}
        <View style={{ height: 20 }} />
      </View>
    </ScrollView>
  )
}

const s = StyleSheet.create({
  scroll:        { flex: 1, backgroundColor: '#0A0A0F' },
  hero:          { height: 200, overflow: 'hidden' },
  heroBg:        { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%', resizeMode: 'cover' },
  heroOverlay:   { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(10,10,15,0.55)' },
  heroContent:   { position: 'absolute', bottom: 20, left: 20 },
  heroLabel:     { color: '#10B981', fontSize: 12, fontWeight: '700', letterSpacing: 2, textTransform: 'uppercase', marginBottom: 4 },
  heroTitle:     { color: '#fff', fontSize: 28, fontWeight: '800', letterSpacing: -0.5 },
  heroSub:       { color: 'rgba(255,255,255,0.5)', fontSize: 12, marginTop: 2 },
  body:          { padding: 16, gap: 12 },
  targetCard:    { backgroundColor: '#111118', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: '#1E1E2A' },
  targetTitle:   { color: '#fff', fontSize: 14, fontWeight: '700', marginBottom: 12 },
  targetRow:     { flexDirection: 'row', justifyContent: 'space-between' },
  targetItem:    { alignItems: 'center' },
  targetVal:     { fontSize: 20, fontWeight: '800' },
  targetUnit:    { color: '#666', fontSize: 10, marginTop: -2 },
  targetLabel:   { color: '#888', fontSize: 11, marginTop: 2 },
  error:         { color: '#EF4444', fontSize: 13, textAlign: 'center' },
  updatedBanner: { backgroundColor: '#1A2E1A', borderRadius: 12, padding: 12, borderWidth: 1, borderColor: '#4ADE8044', alignItems: 'center' },
  updatedText:   { color: '#4ADE80', fontSize: 13, fontWeight: '700', letterSpacing: 0.3 },
  genBtn:        { backgroundColor: '#10B981', borderRadius: 14, padding: 16, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8 },
  genBtnText:    { color: '#fff', fontSize: 15, fontWeight: '700' },
  coachBtn:      { backgroundColor: 'transparent', borderRadius: 14, padding: 14, borderWidth: 1, borderColor: '#7C5CFC44', alignItems: 'center' },
  coachBtnText:  { color: '#7C5CFC', fontSize: 14, fontWeight: '600' },
  mealCard:      { backgroundColor: '#111118', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: '#1E1E2A', gap: 8 },
  mealHeader:    { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  mealTag:       { borderWidth: 1, borderRadius: 20, paddingHorizontal: 10, paddingVertical: 3 },
  mealTagText:   { fontSize: 10, fontWeight: '800', letterSpacing: 1 },
  mealCal:       { color: '#fff', fontSize: 15, fontWeight: '800' },
  mealName:      { color: '#fff', fontSize: 16, fontWeight: '700' },
  macroChips:    { flexDirection: 'row', gap: 8 },
  macroChip:     { backgroundColor: '#1A1A2E', color: '#999', fontSize: 11, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8 },
  ingredients:   { gap: 3, paddingTop: 4, borderTopWidth: 1, borderTopColor: '#1E1E2A' },
  ingredient:    { color: '#666', fontSize: 12 },
  totalsCard:    { backgroundColor: '#111118', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: '#7C5CFC33' },
  totalsTitle:   { color: '#7C5CFC', fontSize: 13, fontWeight: '700', marginBottom: 12, letterSpacing: 0.5, textTransform: 'uppercase' },
  totalsRow:     { flexDirection: 'row', justifyContent: 'space-between' },
  totalItem:     { alignItems: 'center' },
  totalVal:      { color: '#fff', fontSize: 16, fontWeight: '800' },
  totalLabel:    { color: '#666', fontSize: 11, marginTop: 2 },
})
