// mobile/app/(tabs)/workout.tsx
import { useState, useEffect, useCallback } from 'react'
import { View, Text, ScrollView, StyleSheet, TouchableOpacity, Image, ActivityIndicator } from 'react-native'
import AsyncStorage from '@react-native-async-storage/async-storage'
import { useFocusEffect } from 'expo-router'
import { getProfile } from '../../lib/supabase'
import { generateWorkoutPlan, WorkoutPlan } from '../../lib/api'
import { router } from 'expo-router'

const FOCUS_COLORS: Record<string, string> = {
  'Push': '#7C5CFC', 'Pull': '#3B82F6', 'Legs': '#EF4444',
  'Core': '#F59E0B', 'Cardio': '#10B981', 'Rest': '#6B7280', 'Upper': '#8B5CF6', 'Lower': '#EC4899'
}

function getFocusColor(focus: string) {
  return FOCUS_COLORS[Object.keys(FOCUS_COLORS).find(k => focus?.includes(k)) || ''] || '#7C5CFC'
}

export default function WorkoutScreen() {
  const [plan, setPlan]         = useState<WorkoutPlan | null>(null)
  const [loading, setLoading]   = useState(false)
  const [error, setError]       = useState('')
  const [expanded, setExpanded] = useState<number | null>(0)
  const [provider, setProvider] = useState('')
  const [planUpdated, setPlanUpdated] = useState(false)

  // Reload plan every time this tab is focused — picks up AI coach updates instantly
  useFocusEffect(
    useCallback(() => {
      AsyncStorage.getItem('workout_plan').then(p => {
        if (p) {
          const parsed = JSON.parse(p)
          setPlan(prev => {
            if (prev && JSON.stringify(prev) !== JSON.stringify(parsed)) {
              setPlanUpdated(true) // show "Plan Updated!" banner
              setTimeout(() => setPlanUpdated(false), 4000)
            }
            return parsed
          })
          setProvider(parsed._provider || '')
        }
      })
    }, [])
  )

  const generate = async () => {
    setLoading(true); setError('')
    try {
      const profile = await getProfile()
      if (!profile) { setError('Please complete your profile first.'); setLoading(false); return }
      const res = await generateWorkoutPlan({
        gender: profile.gender || 'male',
        age: profile.age || 25,
        goal: profile.goal || 'maintain',
        days: profile.activity === 'sedentary' ? 3 : profile.activity === 'active' ? 6 : 4,
        duration: 45,
        targetPhysique: profile.target_physique || 'athletic'
      })
      setPlan(res)
      setProvider(res._provider || '')
      await AsyncStorage.setItem('workout_plan', JSON.stringify(res))
    } catch (e: any) {
      setError(e.message)
    }
    setLoading(false)
  }

  return (
    <ScrollView style={s.scroll} showsVerticalScrollIndicator={false}>
      {/* Hero */}
      <View style={s.hero}>
        <Image source={require('../../assets/hero_workout.png')} style={s.heroBg} />
        <View style={s.heroOverlay} />
        <View style={s.heroContent}>
          <Text style={s.heroLabel}>Weekly Program</Text>
          <Text style={s.heroTitle}>Your Workout Plan</Text>
          {provider ? <Text style={s.heroSub}>Generated by {provider}</Text> : null}
        </View>
      </View>

      <View style={s.body}>
        {/* AI Updated Banner */}
        {planUpdated && (
          <View style={s.updatedBanner}>
            <Text style={s.updatedText}>✦ Plan updated by AI Coach</Text>
          </View>
        )}
        {!plan && !loading && (
          <View style={s.emptyState}>
            <Text style={s.emptyTitle}>No plan yet</Text>
            <Text style={s.emptySub}>Generate your personalized workout plan based on your goals and activity level.</Text>
          </View>
        )}

        {error ? <Text style={s.error}>{error}</Text> : null}

        <TouchableOpacity style={s.genBtn} onPress={generate} disabled={loading}>
          {loading
            ? <><ActivityIndicator color="#fff" size="small" /><Text style={s.genBtnText}>  Generating...</Text></>
            : <Text style={s.genBtnText}>{plan ? 'Regenerate Plan' : 'Generate My Workout Plan'}</Text>
          }
        </TouchableOpacity>

        <TouchableOpacity style={s.coachBtn} onPress={() => router.push('/(tabs)/chat')}>
          <Text style={s.coachBtnText}>Customize with AI Coach</Text>
        </TouchableOpacity>

        {/* Workout Days */}
        {plan?.plan?.map((day, i) => {
          const color = getFocusColor(day.focus)
          const open  = expanded === i
          return (
            <TouchableOpacity key={i} style={s.dayCard} onPress={() => setExpanded(open ? null : i)} activeOpacity={0.8}>
              <View style={s.dayHeader}>
                <View style={[s.dayAccent, { backgroundColor: color }]} />
                <View style={s.dayInfo}>
                  <Text style={s.dayName}>{day.day}</Text>
                  <Text style={s.dayFocus}>{day.focus}</Text>
                </View>
                <View style={s.dayRight}>
                  <Text style={s.dayExCount}>{day.exercises?.length || 0} exercises</Text>
                  <Text style={[s.chevron, open && s.chevronOpen]}>›</Text>
                </View>
              </View>
              {open && (
                <View style={s.dayBody}>
                  {day.warm_up && <Text style={s.warmup}>Warm-up: {day.warm_up}</Text>}
                  {day.exercises?.map((ex, j) => (
                    <View key={j} style={s.exercise}>
                      <View style={s.exLeft}>
                        <Text style={s.exName}>{ex.name}</Text>
                        {ex.notes && <Text style={s.exNotes}>{ex.notes}</Text>}
                      </View>
                      <View style={s.exRight}>
                        <Text style={s.exSets}>{ex.sets} × {ex.reps}</Text>
                        <Text style={s.exRest}>{ex.rest_sec}s rest</Text>
                      </View>
                    </View>
                  ))}
                  {day.cool_down && <Text style={s.warmup}>Cool-down: {day.cool_down}</Text>}
                </View>
              )}
            </TouchableOpacity>
          )
        })}
      </View>
    </ScrollView>
  )
}

const s = StyleSheet.create({
  scroll:       { flex: 1, backgroundColor: '#0A0A0F' },
  hero:         { height: 200, overflow: 'hidden' },
  heroBg:       { ...StyleSheet.absoluteFillObject, width: '100%', height: '100%', resizeMode: 'cover' },
  heroOverlay:  { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(10,10,15,0.55)' },
  heroContent:  { position: 'absolute', bottom: 20, left: 20 },
  heroLabel:    { color: '#7C5CFC', fontSize: 12, fontWeight: '700', letterSpacing: 2, textTransform: 'uppercase', marginBottom: 4 },
  heroTitle:    { color: '#fff', fontSize: 28, fontWeight: '800', letterSpacing: -0.5 },
  heroSub:      { color: 'rgba(255,255,255,0.5)', fontSize: 12, marginTop: 2 },
  body:         { padding: 16, gap: 12 },
  emptyState:   { backgroundColor: '#111118', borderRadius: 16, padding: 24, alignItems: 'center', gap: 8, borderWidth: 1, borderColor: '#1E1E2A' },
  emptyTitle:   { color: '#fff', fontSize: 17, fontWeight: '700' },
  emptySub:     { color: '#666', fontSize: 14, textAlign: 'center', lineHeight: 20 },
  updatedBanner:{ backgroundColor: '#1A2E1A', borderRadius: 12, padding: 12, borderWidth: 1, borderColor: '#4ADE8044', alignItems: 'center' },
  updatedText:  { color: '#4ADE80', fontSize: 13, fontWeight: '700', letterSpacing: 0.3 },
  error:        { color: '#EF4444', fontSize: 13, textAlign: 'center' },
  genBtn:       { backgroundColor: '#7C5CFC', borderRadius: 14, padding: 16, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8 },
  genBtnText:   { color: '#fff', fontSize: 15, fontWeight: '700' },
  coachBtn:     { backgroundColor: 'transparent', borderRadius: 14, padding: 14, borderWidth: 1, borderColor: '#7C5CFC44', alignItems: 'center' },
  coachBtnText: { color: '#7C5CFC', fontSize: 14, fontWeight: '600' },
  dayCard:      { backgroundColor: '#111118', borderRadius: 16, overflow: 'hidden', borderWidth: 1, borderColor: '#1E1E2A' },
  dayHeader:    { flexDirection: 'row', alignItems: 'center', padding: 16, gap: 12 },
  dayAccent:    { width: 4, height: 44, borderRadius: 2 },
  dayInfo:      { flex: 1 },
  dayName:      { color: '#fff', fontSize: 15, fontWeight: '700' },
  dayFocus:     { color: '#888', fontSize: 12, marginTop: 2 },
  dayRight:     { alignItems: 'flex-end', gap: 4 },
  dayExCount:   { color: '#666', fontSize: 11 },
  chevron:      { color: '#555', fontSize: 22, transform: [{ rotate: '0deg' }] },
  chevronOpen:  { transform: [{ rotate: '90deg' }] },
  dayBody:      { paddingHorizontal: 16, paddingBottom: 16, gap: 10, borderTopWidth: 1, borderTopColor: '#1E1E2A' },
  warmup:       { color: '#666', fontSize: 12, marginTop: 8, fontStyle: 'italic' },
  exercise:     { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#0A0A0F', borderRadius: 10, padding: 12 },
  exLeft:       { flex: 1 },
  exName:       { color: '#fff', fontSize: 14, fontWeight: '600' },
  exNotes:      { color: '#666', fontSize: 11, marginTop: 2 },
  exRight:      { alignItems: 'flex-end', gap: 2 },
  exSets:       { color: '#7C5CFC', fontSize: 13, fontWeight: '700' },
  exRest:       { color: '#555', fontSize: 10 },
})
